name: scheduleapp
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  drift: ^2.4.2
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.2

  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  table_calendar: ^3.0.9
  freezed: ^2.2.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  flutter_riverpod: ^2.2.0
  go_router:
  flutter_hooks: ^0.18.6
  flutter_datetime_picker_plus: ^2.0.1
  hooks_riverpod: ^2.3.1
  flutter_slidable: ^2.0.0
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.5
  syncfusion_flutter_calendar: ^21.1.35
  flutter_datetime_picker: ^1.5.1
  flutter_cupertino_datetime_picker: ^3.0.0
  flutter_localization: ^0.1.13
  build_runner_core: ^7.2.8
  analyzer: ^5.13.0
  logging: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  drift_dev: ^2.11.1
  build_runner: ^2.4.6
  json_serializable: ^6.5.4



flutter:
  uses-material-design: true